url: https://rabernat.github.io
baseurl:
plugins: ['jekyll/scholar']

# Site settings
title: James Doss-Gollin
email: james.doss-gollin@columbia.edu
description: "Statistics + Physics for Climate Risk Management"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00A5D9
  secondary: 807F83
  secondary-dark: 333

# pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:james.doss-gollin@columbia.edu
  - title: twitter
    url: http://twitter.com/jdossgollin
  - title: github
    url: http://github.com/jdossgollin
  - title: medium
    url: https://medium.com/@jdossgollin

# Build settings
markdown: kramdown
permalink: pretty

# Bibliography settings
scholar:
  style: american-geophysical-union

  sort_by: year
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"