url: https://jdossgollin.github.io
baseurl: ""
plugins: ['jekyll-scholar']

# Site settings
title: James Doss-Gollin
email: james.doss-gollin@columbia.edu
description: "Research website of James Doss-Gollin, a Ph.D. Student in Earth and Environmental Engineering at Columbia University, about floods, climate adaptation, risk management, data science, statistics, infrastructure, and water management"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00A5D9
  secondary: 807F83
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:james.doss-gollin@columbia.edu
  - title: github
    url: http://github.com/jdossgollin
  - title: twitter
    url: http://twitter.com/jdossgollin

# Build settings
markdown: kramdown
permalink: pretty

# Bibliography settings
scholar:
  style: american-geophysical-union

  sort_by: year
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"