name: jdossgollin
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.6
    - beautifulsoup4
    - bottleneck
    - cartopy
    - dask
    - ghp-import
    - ipython>=4.0
    - jupyter>=1.0
    - Markdown
    - matplotlib
    - mypy
    - nbconvert>=4.0
    - netcdf4
    - pelican
    - pip
    - pybtex
    - pylint
    - scipy
    - xarray
    - pip:
        - titlecase