review:
  - journal: Journal of Hydrology
    time: 2017--Present
  - journal: Oxford Journal of Development Studies
    time: 2017
professional:
  - position: Organizer
    organization: Columbia Earth and Environmental Engineering Student Research Symposium
    time: 2017--2018
  - position: Member
    organization: American Geophysical Union
    time: 2015--Present
  - position: Member
    organization: American Meteorological Society
    time: 2016--Present
  
outreach:
  - position: Volunteer
    organization: Youth Career Connect
    time: 2016–2017
  - position: Founder and President
    organization: New Haven REACH
    time: 2012-2015